apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: {{ .Values.image.repository }}
          env:
            - name: SVC_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: spring.datasource.url
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: URL
            - name: spring.datasource.driverClass
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: DRIVER
            - name: spring.jpa.properties.hibernate.dialect
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: DIALECT
            - name: spring.datasource.username
              value: username
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: USER_PSWD
            - name: management.metrics.web.server.request.autotime.percentiles
              value: 0.5,0.95,0.99
          ports:
            - name: web
              containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 20
            periodSeconds: 5
