apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: web
  type: {{ .Values.service.type }}
