apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-app
spec:
  selector:
    app: user-app
  ports:
    - name: web
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: web
  type: {{ .Values.service.type }}
