{
 "title": "arch-homework-1",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "INGRESS Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS by status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_request_duration_seconds_count[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Ingress quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "0.50"
    },
    {
     "expr": "histogram_quantile(0.95,sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99,sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Errors rate by status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate(nginx_ingress_controller_request_duration_seconds_count{status =~\"[4-5].*\"}[1m])) by(status)\n",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "POD Level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "graph",
     "description": "Requests per second",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{uri=~\"/user.*\"}[1m])",
       "legendFormat": "{{method}} - {{uri}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Response time (ms)",
     "type": "graph",
     "description": "Response time",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(rate( http_server_requests_seconds_sum[1m]) / rate(http_server_requests_seconds_count[1m])) * 1000",
       "legendFormat": "{{method}} - {{uri}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Quantiles",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds{uri=~\"/user.*\"}",
       "legendFormat": "{{quantile}} - {{method}} - {{uri}} - {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}