spring:
  datasource:
    url: jdbc:mysql://172.17.0.3:3306/userdb
    driverClass: com.mysql.jdbc.Driver
    username: root
    password: test1

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus

  metrics:
    web:
      server:
        request:
          autotime:
            percentiles: 0.5,0.95,0.99