apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: user-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: dmwm/userapp:latest
          ports:
            - containerPort: 8080
